/* automatically generated by rust-bindgen 0.65.1 */

pub use inference_engine_core_sys::*;

extern "C" {
    pub fn inference_engine_ort__create_inference_engine(
        model_data: *const ::std::os::raw::c_void,
        model_data_size_bytes: usize,
        engine: *mut *mut ::std::os::raw::c_void,
    ) -> InferenceEngineResultCode;
}
