# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - directory: "/"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/core-rs"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/ort-cpp"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/ort-cpp/test-model-creator"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  - directory: "/ort-rs"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/ort-sys"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/tflite-cpp"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/tflite-cpp/test-model-creator"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  - directory: "/tflite-rs"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/tflite-sys"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"
