[workspace]
members = ["core"]

[workspace.package]
version = "0.1.0"
publish = false
edition = "2021"

[package]
name = "inference-engine"
version.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
