[tool.poetry]
name = "test-model-creator"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8,<3.12"
tensorflow-macos = { version = "2.13.0", platform = "darwin" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
