/* automatically generated by rust-bindgen 0.65.1 */

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum InferenceEngineResultCode {
    Ok = 0,
    Error = -1,
}
extern "C" {
    pub fn inference_engine__get_last_error_message() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn inference_engine__create_inference_engine(
        model_data: *const ::std::os::raw::c_void,
        model_data_size_bytes: usize,
        engine: *mut *mut ::std::os::raw::c_void,
    ) -> InferenceEngineResultCode;
}
extern "C" {
    pub fn inference_engine__destroy_inference_engine(
        engine: *mut ::std::os::raw::c_void,
    ) -> InferenceEngineResultCode;
}
extern "C" {
    pub fn inference_engine__get_input_count(engine: *const ::std::os::raw::c_void) -> usize;
}
extern "C" {
    pub fn inference_engine__get_output_count(engine: *const ::std::os::raw::c_void) -> usize;
}
extern "C" {
    pub fn inference_engine__get_input_shape(
        engine: *const ::std::os::raw::c_void,
        index: usize,
        shape_data: *mut *const usize,
        shape_size: *mut usize,
    );
}
extern "C" {
    pub fn inference_engine__get_output_shape(
        engine: *const ::std::os::raw::c_void,
        index: usize,
        shape_data: *mut *const usize,
        shape_size: *mut usize,
    );
}
extern "C" {
    pub fn inference_engine__set_input_shape(
        engine: *mut ::std::os::raw::c_void,
        index: usize,
        shape_data: *const usize,
        shape_size: usize,
    ) -> InferenceEngineResultCode;
}
extern "C" {
    pub fn inference_engine__set_output_shape(
        engine: *mut ::std::os::raw::c_void,
        index: usize,
        shape_data: *const usize,
        shape_size: usize,
    ) -> InferenceEngineResultCode;
}
extern "C" {
    pub fn inference_engine__get_input_data(
        engine: *mut ::std::os::raw::c_void,
        index: usize,
    ) -> *mut f32;
}
extern "C" {
    pub fn inference_engine__get_output_data(
        engine: *const ::std::os::raw::c_void,
        index: usize,
    ) -> *const f32;
}
extern "C" {
    pub fn inference_engine__set_input_data(
        engine: *mut ::std::os::raw::c_void,
        index: usize,
        data: *const f32,
    ) -> InferenceEngineResultCode;
}
extern "C" {
    pub fn inference_engine__set_output_data(
        engine: *mut ::std::os::raw::c_void,
        index: usize,
        data: *mut f32,
    ) -> InferenceEngineResultCode;
}
extern "C" {
    pub fn inference_engine__run(engine: *mut ::std::os::raw::c_void) -> InferenceEngineResultCode;
}
