[package]
name = "inference-engine-ort"
version.workspace = true
publish.workspace = true
edition.workspace = true
links = "inference-engine-ort"

[dependencies]
inference-engine-core = { path = "../core" }
inference-engine-ort-sys = { path = "../ort-sys" }
