[package]
name = "inference-engine-tflite"
version.workspace = true
publish.workspace = true
edition.workspace = true
links = "inference_engine_tflite"

[dependencies]
assert_matches = "1.5"
inference-engine-core = { path = "../core" }
inference-engine-tflite-sys = { path = "../tflite-sys" }
