[package]
name = "inference-engine-core-sys"
version.workspace = true
publish.workspace = true
edition.workspace = true

[features]
generate-bindings = ["bindgen"]

[dependencies]
inference-engine-core = { path = "../core-rs" }

[build-dependencies]
bindgen = { version = "0.68", optional = true }
