@echo off

if "%CMAKE_SOURCE_DIR%"=="" set CMAKE_SOURCE_DIR=.
if "%CMAKE_BUILD_DIR%"=="" set CMAKE_BUILD_DIR=build
if "%CMAKE_CONFIG%"=="" set CMAKE_CONFIG=Debug
if "%CMAKE_INSTALL_PREFIX%"=="" set CMAKE_INSTALL_PREFIX=.

if "%INFERENCE_ENGINE_TFLITE_TENSORFLOWLITE_DIR%"=="" set INFERENCE_ENGINE_TFLITE_TENSORFLOWLITE_DIR=''
if "%INFERENCE_ENGINE_TFLITE_TENSORFLOWLITE_VERSION%"=="" set INFERENCE_ENGINE_TFLITE_TENSORFLOWLITE_VERSION=''
if "%INFERENCE_ENGINE_TFLITE_RUN_TESTS%"=="" set INFERENCE_ENGINE_TFLITE_RUN_TESTS=ON
if "%INFERENCE_ENGINE_TFLITE_SYS_RUN_TESTS%"=="" set INFERENCE_ENGINE_TFLITE_SYS_RUN_TESTS=ON

cmake ^
    -S "%CMAKE_SOURCE_DIR%" ^
    -B "%CMAKE_BUILD_DIR%" ^
    -D CMAKE_BUILD_TYPE=%CMAKE_CONFIG% ^
    -D CMAKE_CONFIGURATION_TYPES=%CMAKE_CONFIG% ^
    -D CMAKE_INSTALL_PREFIX="%CMAKE_INSTALL_PREFIX%" ^
    -D INFERENCE_ENGINE_TFLITE_TENSORFLOWLITE_DIR="%INFERENCE_ENGINE_TFLITE_TENSORFLOWLITE_DIR%" ^
    -D INFERENCE_ENGINE_TFLITE_TENSORFLOWLITE_VERSION=%INFERENCE_ENGINE_TFLITE_TENSORFLOWLITE_VERSION% ^
    -D INFERENCE_ENGINE_TFLITE_RUN_TESTS=%INFERENCE_ENGINE_TFLITE_RUN_TESTS% ^
    -D INFERENCE_ENGINE_TFLITE_SYS_RUN_TESTS=%INFERENCE_ENGINE_TFLITE_SYS_RUN_TESTS% ^
    || exit $?

cmake ^
    --build "%CMAKE_BUILD_DIR%" ^
    --config %CMAKE_CONFIG% ^
    --parallel ^
    || exit $?

cmake ^
    --install "%CMAKE_BUILD_DIR%" ^
    --config %CMAKE_CONFIG% ^
    || exit $?
