[package]
name = "inference-engine-tflite-sys"
version.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]

[dev-dependencies]
execute-command = "0.3"

[build-dependencies]
bindgen = "0.65"
const_format = "0.2"
execute-command = "0.3"
